# Generated by Django 5.0.4 on 2024-07-08 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("galeria", "0005_alter_fotografia_foto"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fotografia",
            name="publicada",
            field=models.BooleanField(default=True),
        ),
    ]
